import "./globals.css";

import type { Metadata } from "next";
import React from "react";

import { Body } from "@/components/ui/custom/Body";
import StoreProvider from "@/lib/store/StoreProvidet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <StoreProvider>
      <html lang="en">
        <Body>{children}</Body>
      </html>
    </StoreProvider>
  );
}
